* Healthy programmer

Motivation for this project is to share my long term experience with setting up the working environment
that can help to keep all sitting people fresh and healthy from both mental and physical point of views.
Topics I would like to present are these:

- ergonomic keyboard and wrist support to keep your arms and shoulders in neutral position without upper and lower back bending
- daily exercise routine for flexible body as an compensation to long time sitting during the day
- hardening in cold water in the middle of the work day to recharge the batteries
- multi-workspace environment using tile-based window manager that allows to navigate through applications subconsciously

I am almost 40 years old now (2021-05-25) and I have spent long time behind the computers since my early childhood.
During the Covid 19 difficult year (2020/2021) when everybody else was on home office I was daily commuting to the
open space office and my employer (Gratex International) allowed me to set up new effective working environment.

One year later I would like to share this journey with you.

* Ergonomic keyboard

- [[file:./keyboard/keyboard.org][Construction]]
- [[file:./keyboard/traditional-vs-ergo.org][Natural position of body while sitting]]

Michal
