* Motivation

The body position while sitting on the chair is far away from neutral human body posture. Naturally our muscles, tendons and joints are not developed the way to stay still for longer period of time.
However human body is very adaptive ecosystem and when forced it assimilates slowly to the conditions of the environment. Sitting upright for hours can be very challenging for our neck, upper and lower back.
It requires strong back muscles. But back is not the only body part that is affected. Our knees are constantly bent in the sitting position and often positioned in stained angle. Our tights, calfs and ankles
are unused and progressively becoming tight.
Our shoulders, forearms and wrists are kept rotated for hours from their comfortable state in order to ensure convenience while typing on the keyboard or using the mouse.
With years some muscles and tendons are slowly getting prolonged and others shortened which may result in muscle/tendon disbalances in the limbs, back and core.
Without moving our muscles are losing their original flexibility. As a result the joints, bones and spine vertebras are now responsible for body support body instead of muscles and tendons.
All these factors combined together may result in chronic pain and damage of the musculoskeletal system.
In order to avoid unfavorable body changes caused by incorrect sitting without frequent breaks compensation power exercises and stretching are more than recommended.

* Incorrect sitting position

* Correct sitting position

* Affected body parts and related exercises

** Neck, lower and upper back, shoulders

** Arms: Wrists and forearms

** Legs: Tights, calfs and ankles

** Gluts

** Body core
