* Multiple workspaces

As developers, we often work with multiple software applications. If there are only a few windows to operate,
Alt+Tab as a switch between them is sufficient. But at some point, in terms of efficiency, we often become so-called
"heavy users," interacting with dozens of windows, console terminals, etc. The more applications are being used,
the more challenging navigation between them becomes. At this point, using virtual workspaces is an effective
solution. Application windows can be positioned on dedicated workspaces. It is good to continuously add new
application windows to dedicated workspaces. Over time, you will memorize their placement, and then navigation
becomes a subconscious process, which dramatically enhances programmer performance.

Choosing a tiling window manager is another step toward higher performance. There can be multiple application
windows positioned on a virtual workspace, and with a tiling window manager, you can navigate between application
windows by using the keyboard.




  TODO

  Navigation, subcoscious navigation, scripting what is typed, less of mouse, mouse motion cannot be scripted
  Mental focus on navigation takes energy,
  Tiled window manager
  link to i3m config here
 (TODO: document i3 wm setup, worskpaces, init script after computer restart)
  project a workspace to be more detailed, explain sub windows for Project A.

mu4e and emailing without using mouse, quick emailing

* Ergonomic keyboard and multiple workspaces

Ergonomic keyboards are designed to provide enhanced comfort for the typist's fingers, especially for pinkies, which are heavily
overloaded in the programming profession as they are responsible for keys such as:
right parenthesis, both square brackets, curly brackets, pipe, backslash, dash, underscore, escape, tilde, backspace,
and on some types of traditional keyboards, backtick too. Traditionally, pinkies are also supposed to operate modifier keys including
Shift, Control, and GUI key.
Ergonomic keyboards, especially those with a split feature, employ thumbs for some of the above-mentioned keystrokes.
Some ergonomic keyboards with alternative key behavior on press and hold allow the typist to use home keys for modifiers as well,
as depicted in the schema below. For example, when 's' is pressed, it is a regular 's' key, but on hold, it is the ALT modifier.
For some keyboards, this behavior can be fully configured based on the particular typist's preference.

Example of such ergonomic keyboards are those with QMK firemware.

https://docs.qmk.fm/#/

This is my best personal preference and full configuration can be found here:

https://github.com/healthy-programmer/qmk_firmware/tree/michalkelemen/keyboards/keebio/iris/keymaps/michalkelemen

   #+begin_src c

     /*
       ┌────────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬────────┐
        BTICK,   1,     2,     3,     4,     5,                      6,     7,     8,     9,     0,     PSCR,
       ├────────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼────────┤
        TAB,                                                                                            MINS,
       ├────────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼────────┤
        TILD,    A/LAY, S/ALT, D/CTRL,F/LAY,                                J/LAY, K/CTRL,L/ALT, ;/LAY, QUOTE,
       ├────────┼──────┼──────┼──────┼──────┼──────┼──────┐┌────────┼──────┼──────┼──────┼──────┼──────┼────────┤
        BSLASH,                                                                                         EQL,
       └────────┴──────┴──────┴─┬────┴───┬──┴───┬──┴───┬──┘└───┬────┴───┬──┴───┬──┴───┬──┴──────┴──────┴────────┘
                                 GUI/ESC, SPACE, SHIFT,         BSPACE,  SHIFT, GUI/ENTER
                                └────────┴──────┴──────┘       └────────┴──────┴──────┘

     Or in particular, usage of workspaces like this:
     Once I started to be a heavy user of Linux multi-workspace, documentation became a high-priority must.
     
            ┌────────┬──────┬──────┬──────┬──────┬──────┐                ┌──────┬──────┬──────┬──────┬──────┬────────┐
                      MUM,   SUU,   CORE, RIEMANN, STUDY                  KEY,   CAMUN, GARB,  WS-SET, CLOJ,  ENV,
                                          KONAN
                                          KUBECTL
            ├────────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼────────┤
                                                                                             JENKINS,
            ├────────┼──────┼──────┼──────┼──────┼──────┤                ├──────┼──────┼──────┼──────┼──────┼────────┤
                                                                                             EMAIL,
            ├────────┼──────┼──────┼──────┼──────┼──────┼──────┐┌────────┼──────┼──────┼──────┼──────┼──────┼────────┤
                                                                                             TODOs,
                                                                                             DAILY AGENDA,
                                                                                             DIARY NOTEs,
                                                                                             KNOWLEDGE BASE
            └────────┴──────┴──────┴─┬────┴───┬──┴───┬──┴───┬──┘└───┬────┴───┬──┴───┬──┴───┬──┴──────┴──────┴────────┘
     
                                     └────────┴──────┴──────┘       └────────┴──────┴──────┘
          ,*/

   #+end_src

Now let's get back to the multiple workspaces topic. Usually, we use MOD+1, MOD+2, ... for switching between workspaces.
But now, when pinkies are free, instead of operating modifier keys, they can operate regular keys. As a beneficial consequence of this,
you can end up with the solution described in the following table.
As you can see, the keys representing workspaces are logically the border keys on the keyboard layout, which
is easy to memorize and, personally, very comfortable for me. Especially, often-switched workspaces (quick notes, email communication)
are conveniently available under the Quote and Equal keys (workspaces 13 and 14).

| ID | Navigation         | Workspace Purpose                                                            |
|----+--------------------+------------------------------------------------------------------------------|
|  1 | GUI + 1            | Project A workspace                                                          |
|  2 | GUI + 2            | Project B workspace                                                          |
|  3 | GUI + 3            | Project C workspace                                                          |
|  4 | GUI + 4            | Project D workspace                                                          |
|  5 | GUI + 5            |                                                                              |
|  6 | GUI + 6            | Study, Keboards, Healthy Programmer, Typing practice                         |
|  7 | GUI + 7            |                                                                              |
|  8 | GUI + 8            | Text buffer for stacktrace investigation                                     |
|  9 | GUI + 9            |                                                                              |
| 10 | GUI + 10           |                                                                              |
| 11 | GUI + Print Screen | Application environments, logins and passwords                               |
| 12 | GUI + Minus        | Build and deployment                                                         |
| 13 | GUI + Quote        | Email communication                                                          |
| 14 | GUI + Equal        | General TODO List / Quick Notes in org file, Jira web page for current tasks |
| 15 | GUI + Back Tick    | Reserved                                                                     |
| 16 | GUI + Tab          | Reserved                                                                     |
| 17 | GUI + Tild         | Reserved                                                                     |
| 18 | GUI + Back Slah    | Reserved                                                                     |

* Tile-based window manager

Personally, I've decided to use the i3 window manager:

https://i3wm.org/

My custom i3 configuration can be found here:

[[./config][Custom i3 Configuration]]

My init script that initializes all virtual workspaces is available below:

[[./i3init.sh][i3 Init Script]]
